language: nix
nix: 2.1.1

git:
  quiet: true

script:
  # Install netorcai
  - nix-env --quiet -f https://github.com/netorcai/pkgs/archive/master.tar.gz -iA netorcai_dev
  - netorcai --version

  # Install gfortran & gcovr (from unstable) and ninja & meson (from stable)
  - nix-env --quiet -f https://github.com/NixOS/nixpkgs/archive/18.09.tar.gz -iA gfortran pythonPackages.gcovr
  - nix-env --quiet -f https://github.com/NixOS/nixpkgs/tarball/bae9fd59a945357f7712a63c0a09b72d4ed44e6e -iA ninja meson
  - gfortran --version
  - ninja --version
  - meson --version

  # Run unit tests with coverage
  - meson build -Db_coverage=true
  - ninja -C build
  - ninja -C build test
  - ninja -C build coverage-text

  # print coverage report
  - cat build/meson-logs/coverage.txt

  # send coverage results to codecov.io
  - bash <(curl -s https://codecov.io/bash)

  # install doveralls and send coverage results with it
  #- nix-shell -p wget --command 'wget -O ./doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.1/doveralls_linux_travis"'
  #- chmod +x ./doveralls
  #- ./doveralls

  # TODO: build and run the example GL and player

